spring:
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    user: learning_postgres_owner
    password: t8qELP1OjCFp
    enabled: false
  application:
    name: accounts
  jpa:
    hibernate:
      ddl-auto: validate
#      ddl-auto: create-drop
#      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://ep-soft-recipe-a189x52v.ap-southeast-1.aws.neon.tech/metaverse?sslmode=require
    #    url: jdbc:postgresql://ep-soft-recipe-a189x52v.ap-southeast-1.aws.neon.tech/test?sslmode=require
    username: learning_postgres_owner
    password: t8qELP1OjCFp
    driver-class-name: org.postgresql.Driver
server:
  port: 8080